import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const root = fileURLToPath(new URL('..', import.meta.url));
const metadata = JSON.parse(await readFile(path.join(root, 'metadata.json'), 'utf8'));
const { version } = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8'));
const start = '<!-- ICON_CATALOG:START -->';
const end = '<!-- ICON_CATALOG:END -->';
const escape = value => value.replace(/[&<>"']/g, ch => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
}[ch]));
const groups = ['LLM', 'Provider', 'Agent'];
const unknown = metadata.flatMap(icon => icon.groups || [icon.group]).filter(group => !groups.includes(group));
if (unknown.length) throw new Error(`Add README columns for new groups: ${[...new Set(unknown)]}`);
const columns = groups.map(group => metadata
  .filter(icon => (icon.groups || [icon.group]).includes(group))
  .sort((a, b) => a.name.localeCompare(b.name, 'en')));
const cdn = `https://cdn.jsdelivr.net/npm/@zenmux/icons@${version}`;
const cells = new Map();
for (const icon of metadata) {
  // Preserve colored artwork. Monochrome artwork gets source-derived surface
  // variants so white originals remain visible in GitHub's light README theme.
  const source = await readFile(path.join(root, 'icons', `${icon.id}.svg`));
  const { data, info } = await sharp(source).resize({ height: 32 }).ensureAlpha().raw()
    .toBuffer({ resolveWithObject: true });
  let colored = false;
  for (let i = 0; i < data.length; i += info.channels) {
    if (data[i + 3] > 32 && Math.max(...data.subarray(i, i + 3)) - Math.min(...data.subarray(i, i + 3)) > 10) {
      colored = true;
      break;
    }
  }
  const name = escape(icon.name);
  const href = `https://zenmux.ai/icons/${encodeURIComponent(icon.id)}`;
  const image = colored
    ? `<img src="${cdn}/icons/${icon.id}.svg" alt="${name}" height="48">`
    : `<picture><source media="(prefers-color-scheme: dark)" srcset="${cdn}/static/dark/${icon.id}.svg"><img src="${cdn}/static/light/${icon.id}.svg" alt="${name}" height="48"></picture>`;
  cells.set(icon.id, `<a href="${href}">${image}<br>${name}</a>`);
}
const lines = [
  start,
  '<!-- Generated by scripts/generate-readme.mjs from metadata.json and icons/. -->',
  '<table>',
  `  <thead><tr>${groups.map(group => `<th>${group}</th>`).join('')}</tr></thead>`,
  '  <tbody>',
];
for (let row = 0; row < Math.max(...columns.map(column => column.length)); row++) {
  lines.push('    <tr>');
  for (const column of columns) {
    lines.push(`      <td width="33%">${column[row] ? cells.get(column[row].id) : ''}</td>`);
  }
  lines.push('    </tr>');
}
lines.push('  </tbody>', '</table>', end);
const file = path.join(root, 'README.md');
const original = await readFile(file, 'utf8');
const from = original.indexOf(start), to = original.indexOf(end);
if (from < 0 || to < from) throw new Error('README catalog markers are missing');
const updated = original.slice(0, from) + lines.join('\n') + original.slice(to + end.length);
if (process.argv.includes('--check')) {
  if (updated !== original) throw new Error('README catalog is stale; run npm run generate:readme');
} else {
  await writeFile(file, updated);
}
console.log(`README catalog: ${metadata.length} brands; ${groups.map((group, i) => `${group} ${columns[i].length}`).join(', ')}.`);
